version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://db:27017/mydb
    depends_on:
      - db
  db:
    image: mongo:4.4.6-bionic
    ports:
      - '27017:27017'
